name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@1d241e9fc733fd98b3e8a729e4ab2873b856157f # v4.2.0
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install


      - name: Build project
        run: npm run build

      - name: Upload build output
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda996908657 # v3.0.1
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164db5ed86f2b6a760b57818e079d4e83f # v4.0.5
